language: c
sudo: true
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - TESTS=true
  matrix:
    - OCAML_VERSION=4.03.0 PACKAGE="ppx_deriving_cmdliner"
    - OCAML_VERSION=4.04.0 PACKAGE="ppx_deriving_cmdliner"
    - OCAML_VERSION=4.05.0 PACKAGE="ppx_deriving_cmdliner"
    - OCAML_VERSION=4.06.0 PACKAGE="ppx_deriving_cmdliner"
    - OCAML_VERSION=4.07.0 PACKAGE="ppx_deriving_cmdliner"
os:
- linux
- osx

